import { auth } from "@/auth";
import AdminSideBar from "@/components/admin/AdminSidebar";
import { Card } from "@/components/ui/card";
import { Metadata } from "next";
import { notFound, redirect } from "next/navigation";

export const metadata: Metadata = {
  title: {
    default: "Admin",
    template: "%s | House Rental",
  },
  description: "Generated by create next app",
};
export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  if (!session || session.user.role !== "admin") {
    return redirect("/auth/login");
  }

  return (
    <div className="flex p-4 gap-2">
      <AdminSideBar />
      <Card className="flex-1 md:min-h-svh md:min-w-max space-y-8 print:border-none print:shadow-none">
        {children}
      </Card>
    </div>
  );
}
