import { auth } from "@/auth";
import EditProfileForm from "@/components/profile/EditProfileForm";
import {
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import db from "@/lib/db";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Edit Profile",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await auth();
  const user = await db.user.findUnique({
    where: { id: session?.user.id },
    select: {
      address: true,
      username: true,
      occupation: true,
      phoneNo: true,
      gender: true,
      id: true,
    },
  });
  return (
    <>
      <CardHeader>
        <CardTitle className="text-2xl">Edit profile information</CardTitle>
        <CardDescription>
          This is how you will see your all activity on the site.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <EditProfileForm user={user} />
      </CardContent>
    </>
  );
}
