import MaxWidthWrapper from "@/components/MaxWithWrapper";
import FilterProperty from "@/components/property/FilterProperty";
import PropertyResult from "@/components/property/PropertyResult";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
import { PropertyFilterValue } from "@/lib/validation";
import { Loader2 } from "lucide-react";
import { Metadata } from "next";
import { Suspense } from "react";

interface PageProps {
  searchParams: {
    q?: string;
    status?: string;
    type?: string;
    city?: string;
    country?: string;
    bedrooms?: string;
    bathrooms?: string;
    hasWoodenCeiling?: string;
    hasParking?: string;
    hasCentralHeating?: string;
    hasAlarm?: string;
    hasSwimmingPool?: string;
    hasLaundryRoom?: string;
    page?: string;
  };
}
export const metadata: Metadata = {
  title: "Find property",
  description: "Generated by create next app",
};

export default async function Page({ searchParams }: PageProps) {
  const {
    q,
    status,
    type,
    city,
    country,
    bedrooms,
    bathrooms,
    hasWoodenCeiling,
    hasParking,
    hasCentralHeating,
    hasAlarm,
    hasSwimmingPool,
    hasLaundryRoom,
    page,
  } = searchParams;

  const filterValues: PropertyFilterValue = {
    q,
    status,
    type,
    city,
    bedrooms,
    country,
    bathrooms,
    hasWoodenCeiling: hasWoodenCeiling === "true",
    hasParking: hasParking === "true",
    hasCentralHeating: hasCentralHeating === "true",
    hasAlarm: hasAlarm === "true",
    hasSwimmingPool: hasSwimmingPool === "true",
    hasLaundryRoom: hasLaundryRoom === "true",
  };

  return (
    <div className=" relative">
      <MaxWidthWrapper>
        <section className="grid grid-cols-1 lg:grid-cols-3 gap-4 relative">
          <div className="relative">
            <div className="hidden md:block sticky top-24">
              <FilterProperty defaultValues={filterValues} />
            </div>
            <div>
              <Dialog>
                <DialogTrigger asChild className="block md:hidden">
                  <Button variant="outline">Filter</Button>
                </DialogTrigger>
                <DialogContent className="sm:max-w-[425px]">
                  <FilterProperty defaultValues={filterValues} />
                </DialogContent>
              </Dialog>
            </div>
          </div>

          <div className="lg:col-span-2 space-y-4">
            <div className="flex flex-col space-y-3">
              <Suspense
                fallback={
                  <div className="w-full mt-24 flex justify-center">
                    <div className="flex flex-col items-center gap-1">
                      <Loader2 className="h-8 w-8 animate-spin text-primary" />
                      <h3>Loading properties...</h3>
                    </div>
                  </div>
                }
              >
                <PropertyResult
                  filterValues={filterValues}
                  page={page ? parseInt(page) : undefined}
                />
              </Suspense>
            </div>
          </div>
        </section>
      </MaxWidthWrapper>
    </div>
  );
}
