import { PropertyFilterValue } from "@/lib/validation";
import { Loader2 } from "lucide-react";
import { Metadata } from "next";
import { Suspense } from "react";

interface PageProps {
  searchParams: {
    q?: string;
    status?: string;
    type?: string;
    city?: string;
    country?: string;
    bedrooms?: string;
    bathrooms?: string;
    hasWoodenCeiling?: string;
    hasParking?: string;
    hasCentralHeating?: string;
    hasAlarm?: string;
    hasSwimmingPool?: string;
    hasLaundryRoom?: string;
    page?: string;
  };
}
export const metadata: Metadata = {
  title: "Find property",
  description: "Generated by create next app",
};

export default async function Page({ searchParams }: PageProps) {
  const {
    q,
    status,
    type,
    city,
    country,
    bedrooms,
    bathrooms,
    hasWoodenCeiling,
    hasParking,
    hasCentralHeating,
    hasAlarm,
    hasSwimmingPool,
    hasLaundryRoom,
    page,
  } = searchParams;

  const filterValues: PropertyFilterValue = {
    q,
    status,
    type,
    city,
    bedrooms,
    country,
    bathrooms,
    hasWoodenCeiling: hasWoodenCeiling === "true",
    hasParking: hasParking === "true",
    hasCentralHeating: hasCentralHeating === "true",
    hasAlarm: hasAlarm === "true",
    hasSwimmingPool: hasSwimmingPool === "true",
    hasLaundryRoom: hasLaundryRoom === "true",
  };

  return (
    <div className="space-y-8 my-10 relative">
      <div className="flex flex-col space-y-3 justify-center items-center text-center px-4 sm:px-8">
        <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold">
          Properties Listing
        </h3>
        <p className="text-muted-foreground text-sm sm:text-base">
          Find your favorite properties
        </p>
      </div>

      <MaxWidthWrapper>
        <section className="grid grid-cols-1 lg:grid-cols-3 gap-4 relative">
          <FilterProperty />

          <div className="lg:col-span-2 space-y-4">
            <div className="flex flex-col space-y-3">
              <Suspense
                fallback={
                  <div className="w-full mt-24 flex justify-center">
                    <div className="flex flex-col items-center gap-1">
                      <Loader2 className="h-8 w-8 animate-spin text-primary" />
                      <h3>Loading properties...</h3>
                    </div>
                  </div>
                }
              >
                <PropertyResult
                  filterValues={filterValues}
                  page={page ? parseInt(page) : undefined}
                />
              </Suspense>
            </div>
          </div>
        </section>
      </MaxWidthWrapper>
    </div>
  );
}
