const dummyProperties = [
  {
    id: "1",
    slug: "luxury-apartment-dhanmondi",
    propertyTitle: "Luxury Apartment in Dhanmondi",
    status: "For Sale",
    type: "Apartment",
    area: 1800.5,
    rooms: 5,
    price: 15000000,
    bathrooms: 3,
    imagesUrl: [
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/1.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/2.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/4.jpg",
    ],
    address: "Road 10A, Dhanmondi",
    city: "Dhaka",
    country: "Bangladesh",
    details:
      "A spacious apartment in the heart of Dhanmondi with modern amenities.",
    buildingAge: 2,
    bedrooms: 4,
    hasParking: true,
    hasSwimmingPool: false,
    hasLaundryRoom: true,
    hasWoodenCeiling: false,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Ali Khan",
    contactEmail: "ali.khan@example.com",
    contactPhone: "+8801712345678",
    userId: "8ec748ec-043f-4e10-a7d6-d0a2aea94a0f",
    createdAt: "2024-12-06T00:00:00Z",
    updateAt: "2024-12-06T00:00:00Z",
  },
  {
    id: "2",
    slug: "modern-flat-gulshan",
    propertyTitle: "Modern Flat in Gulshan",
    status: "For Rent",
    type: "Flat",
    area: 1500,
    rooms: 4,
    price: 70000,
    bathrooms: 2,
    imagesUrl: [
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/1.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/2.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/4.jpg",
    ],
    address: "Gulshan Avenue",
    city: "Dhaka",
    country: "Bangladesh",
    details: "A stylish flat ideal for corporate professionals.",
    buildingAge: 1,
    bedrooms: 3,
    hasParking: true,
    hasSwimmingPool: true,
    hasLaundryRoom: true,
    hasWoodenCeiling: true,
    hasCentralHeating: false,
    hasAlarm: false,
    contactName: "Rahim Uddin",
    contactEmail: "rahim.uddin@example.com",
    contactPhone: "+8801812345678",
    userId: "8ec748ec-043f-4e10-a7d6-d0a2aea94a0f",
    createdAt: "2024-12-05T00:00:00Z",
    updateAt: "2024-12-05T00:00:00Z",
  },
  {
    id: "3",
    slug: "beach-villa-coxs-bazar",
    propertyTitle: "Beach Villa in Cox's Bazar",
    status: "For Sale",
    type: "Villa",
    area: 2500,
    rooms: 6,
    price: 30000000,
    bathrooms: 4,
    imagesUrl: [
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/1.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/2.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/4.jpg",
    ],
    address: "Marine Drive Road",
    city: "Cox's Bazar",
    country: "Bangladesh",
    details: "A luxurious villa with a private beachfront.",
    buildingAge: 3,
    bedrooms: 5,
    hasParking: true,
    hasSwimmingPool: true,
    hasLaundryRoom: true,
    hasWoodenCeiling: true,
    hasCentralHeating: true,
    hasAlarm: true,
    contactName: "Salma Begum",
    contactEmail: "salma.begum@example.com",
    contactPhone: "+8801912345678",
    userId: "8ec748ec-043f-4e10-a7d6-d0a2aea94a0f",
    createdAt: "2024-11-25T00:00:00Z",
    updateAt: "2024-11-25T00:00:00Z",
  },
  {
    id: "4",
    slug: "cozy-house-chattogram",
    propertyTitle: "Cozy House in Chattogram",
    status: "For Rent",
    type: "House",
    area: 1200,
    rooms: 3,
    price: 40000,
    bathrooms: 2,
    imagesUrl: [
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/1.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/2.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/4.jpg",
    ],
    address: "Panchlaish, Chattogram",
    city: "Chattogram",
    country: "Bangladesh",
    details: "A cozy family house with a beautiful garden.",
    buildingAge: 5,
    bedrooms: 2,
    hasParking: false,
    hasSwimmingPool: false,
    hasLaundryRoom: false,
    hasWoodenCeiling: false,
    hasCentralHeating: false,
    hasAlarm: false,
    contactName: "Mizanur Rahman",
    contactEmail: "mizan.rahman@example.com",
    contactPhone: "+8801712341234",
    userId: "8ec748ec-043f-4e10-a7d6-d0a2aea94a0f",
    createdAt: "2024-12-01T00:00:00Z",
    updateAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "5",
    slug: "commercial-space-motijheel",
    propertyTitle: "Commercial Space in Motijheel",
    status: "For Rent",
    type: "Commercial",
    area: 5000,
    rooms: 10,
    price: 200000,
    bathrooms: 4,
    imagesUrl: [
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/1.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/2.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/4.jpg",
    ],
    address: "Motijheel Commercial Area",
    city: "Dhaka",
    country: "Bangladesh",
    details: "Prime office space in Dhaka's business hub.",
    buildingAge: 10,
    bedrooms: 0,
    hasParking: true,
    hasSwimmingPool: false,
    hasLaundryRoom: false,
    hasWoodenCeiling: false,
    hasCentralHeating: true,
    hasAlarm: true,
    contactName: "Nusrat Jahan",
    contactEmail: "nusrat.jahan@example.com",
    contactPhone: "+8801612345678",
    userId: "8ec748ec-043f-4e10-a7d6-d0a2aea94a0f",
    createdAt: "2024-12-03T00:00:00Z",
    updateAt: "2024-12-03T00:00:00Z",
  },
  {
    id: "6",
    slug: "resort-sylhet",
    propertyTitle: "Exclusive Resort in Sylhet",
    status: "For Sale",
    type: "Resort",
    area: 10000,
    rooms: 15,
    price: 50000000,
    bathrooms: 10,
    imagesUrl: [
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/1.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/2.jpg",
      "https://spruko.com/demo/shifto/shifto/assets/images/products/products/modal/4.jpg",
    ],
    address: "Jaflong Road, Sylhet",
    city: "Sylhet",
    country: "Bangladesh",
    details: "A beautiful resort surrounded by tea gardens.",
    buildingAge: 8,
    bedrooms: 15,
    hasParking: true,
    hasSwimmingPool: true,
    hasLaundryRoom: true,
    hasWoodenCeiling: false,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Imran Hossain",
    contactEmail: "imran.hossain@example.com",
    contactPhone: "+8801912341234",
    userId: "8ec748ec-043f-4e10-a7d6-d0a2aea94a0f",
    createdAt: "2024-12-04T00:00:00Z",
    updateAt: "2024-12-04T00:00:00Z",
  },
];
module.exports = { dummyProperties };
