const dummyProperties = [
  {
    id: "1",
    slug: "spacious-apartment-in-gulshan",
    propertyTitle: "Spacious Apartment in Gulshan",
    status: "accepted",
    type: "apartment",
    area: 850,
    rooms: 3,
    price: 8000,
    bathrooms: 2,
    bedrooms: 3,
    address: "House 12, Road 7, Gulshan 1",
    city: "Dhaka",
    country: "Bangladesh",
    details:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 5,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-2.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-3.jpg",
    ],
    hasParking: true,
    hasSwimmingPool: false,
    hasLaundryRoom: true,
    hasWoodenCeiling: false,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
  {
    id: " 2",
    slug: "affordable-house-in-mirpur",
    propertyTitle: "Affordable House in Mirpur",
    status: "accepted",
    type: "houses",
    area: 600,
    rooms: 4,
    price: 5000,
    bathrooms: 2,
    bedrooms: 4,
    address: "Sector 10, Mirpur",
    city: "Dhaka",
    country: "Bangladesh",
    details:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 7,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-4.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-1.jpg",
    ],
    hasParking: false,
    hasSwimmingPool: false,
    hasLaundryRoom: false,
    hasWoodenCeiling: true,
    hasCentralHeating: false,
    hasAlarm: false,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
  {
    id: "3",
    slug: "luxury-apartment-in-dhanmondi",
    propertyTitle: "Luxury Apartment in Dhanmondi",
    status: "accepted",
    type: "apartment",
    area: 950,
    rooms: 4,
    price: 9500,
    bathrooms: 3,
    bedrooms: 4,
    address: "Road 16, Dhanmondi",
    city: "Dhaka",
    country: "Bangladesh",
    details:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 3,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-2.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-3.jpg",
    ],
    hasParking: true,
    hasSwimmingPool: true,
    hasLaundryRoom: true,
    hasWoodenCeiling: false,
    hasCentralHeating: true,
    hasAlarm: true,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
  {
    id: "4",
    slug: "modern-house-in-uttara",
    propertyTitle: "Modern House in Uttara",
    status: "accepted",
    type: "houses",
    area: 700,
    rooms: 3,
    price: 7500,
    bathrooms: 2,
    bedrooms: 3,
    address: "Sector 5, Uttara",
    city: "Dhaka",
    country: "Bangladesh",
    details:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 2,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-4.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-1.jpg",
    ],
    hasParking: true,
    hasSwimmingPool: false,
    hasLaundryRoom: true,
    hasWoodenCeiling: false,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
  {
    id: "5",
    slug: "cozy-apartment-in-banani",
    propertyTitle: "Cozy Apartment in Banani",
    status: "accepted",
    type: "apartment",
    area: 750,
    rooms: 2,
    price: 7000,
    bathrooms: 1,
    bedrooms: 2,
    address: "House 20, Road 12, Banani",
    city: "Dhaka",
    country: "Bangladesh",
    details:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 4,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-2.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-3.jpg",
    ],
    hasParking: true,
    hasSwimmingPool: false,
    hasLaundryRoom: true,
    hasWoodenCeiling: false,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
  {
    id: "6",
    slug: "family-home-in-chattogram",
    propertyTitle: "Family Home in Chattogram",
    status: "accepted",
    type: "houses",
    area: 900,
    rooms: 5,
    price: 10000,
    bathrooms: 3,
    bedrooms: 5,
    address: "Patharghata",
    city: "Chattogram",
    country: "Bangladesh",
    details:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 6,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-4.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-1.jpg",
    ],
    hasParking: true,
    hasSwimmingPool: true,
    hasLaundryRoom: true,
    hasWoodenCeiling: true,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
  {
    id: "7",
    slug: "stylish-apartment-in-sylhet",
    propertyTitle: "Stylish Apartment in Sylhet",
    status: "accepted",
    type: "apartment",
    area: 800,
    rooms: 3,
    price: 8500,
    bathrooms: 2,
    bedrooms: 3,
    address: "Zindabazar",
    city: "Sylhet",
    country: "Bangladesh",
    details:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 3,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-2.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-3.jpg",
    ],
    hasParking: false,
    hasSwimmingPool: false,
    hasLaundryRoom: true,
    hasWoodenCeiling: true,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
  {
    id: "8",
    slug: "charming-house-in-rajshahi",
    propertyTitle: "Charming House in Rajshahi",
    status: "accepted",
    type: "houses",
    area: 750,
    rooms: 4,
    price: 9000,
    bathrooms: 2,
    bedrooms: 4,
    address: "Kazla",
    city: "Rajshahi",
    country: "Bangladesh",
    details:
      "A charming and well-maintained house in a quiet neighborhood. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis aliquam suscipit inventore sequi, adipisci quas et quae fuga fugit, tenetur doloribus commodi. Sequi cum repellat animi cupiditate quidem mollitia nesciunt necessitatibus magni rem odit possimus quibusdam aliquid enim iure, amet earum quia consequatur quo veniam in consectetur? Inventore eius in voluptatum! Et deserunt quos fuga sed necessitatibus accusantium laudantium ipsum! Velit nihil minima veritatis nam ratione corrupti exercitationem vero hic quod cum nesciunt fugiat ex ducimus repudiandae dicta nobis molestias quo eos, sed perspiciatis consequuntur libero, rem doloremque reprehenderit. Aperiam quibusdam at aspernatur necessitatibus rem? Non quae, corrupti magni numquam modi earum labore ad debitis impedit? Ad tenetur minima aliquam corrupti illo praesentium quisquam quasi tempora voluptatem fugit. Fugiat deserunt dicta labore quas dolor cumque placeat id ut, aliquid voluptatum? Aspernatur dolore voluptatibus labore, quod voluptas ullam doloribus rem odit beatae vitae cupiditate ex voluptates velit quibusdam voluptatum odio doloremque? Consectetur rem atque voluptas hic! Perferendis, error possimus consequuntur aspernatur mollitia blanditiis sit laudantium recusandae rerum eos veritatis nisi, praesentium illum enim tempora vero adipisci quam, laboriosam repudiandae? Hic error, quas, est nihil architecto ipsum quasi nostrum iure eaque, dolorem repudiandae! Corporis minus dolorem optio aperiam placeat laudantium alias dolorum quos veritatis, vitae incidunt iusto labore molestiae quam, doloribus deleniti at recusandae porro? Maiores, rem dolor dolorem magnam et voluptate? Voluptate, recusandae architecto sed accusantium error, earum harum doloremque corrupti velit tempore fugit necessitatibus ratione! Recusandae tempore alias, quos dolores quibusdam similique ea a minima. Quidem, harum vero molestias labore reprehenderit quod nisi aspernatur id velit voluptates itaque veritatis fuga dolorem, exercitationem nulla numquam nemo. Eligendi eveniet alias consectetur voluptatum sunt sapiente corporis autem impedit debitis laborum optio modi cum, recusandae ipsam. Distinctio, voluptatibus quibusdam non asperiores voluptate delectus aspernatur aperiam facilis dicta cupiditate similique itaque eos nobis mollitia veniam!",
    buildingAge: 4,
    imagesUrl: [
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-4.jpg",
      "https://storage.googleapis.com/theme-vessel-items/checking-sites/nest-2-html/HTML/main/img/properties/properties-1.jpg",
    ],
    hasParking: true,
    hasSwimmingPool: false,
    hasLaundryRoom: false,
    hasWoodenCeiling: true,
    hasCentralHeating: false,
    hasAlarm: true,
    contactName: "Hasibul Hasan Rokib",
    contactEmail: "rokib4000@gmail.com",
    contactPhone: "01929351427",
    userId: "ce6f40e4-18e9-4277-a94b-112ec3e4727e",
  },
];

module.exports = { dummyProperties };
