import db from "@/lib/db";
import { columns } from "./columns";
import { DataTable } from "./data-table";
import { auth } from "@/auth";
import {
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "My properties",
  description: "Generated by create next app",
};
export default async function Page() {
  const session = await auth();
  const properties = await db.property.findMany({
    where: {
      userId: session?.user.id,
    },
    orderBy: { createdAt: "desc" },
  });
  return (
    <>
      <CardHeader>
        <CardTitle className="text-2xl">My Property lists</CardTitle>
        <CardDescription>
          This is how others will see you on the site.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <DataTable columns={columns} data={properties} />
      </CardContent>
    </>
  );
}
