import { auth } from "@/auth";
import AddPropertyForm from "@/components/property/AddPropertyForm";
import {
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import { notFound } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Add Property",
  description: "Generated by create next app",
};
export default async function Page() {
  const session = await auth();
  if (session?.user.role !== "owner") return notFound();
  return (
    <>
      <CardHeader>
        <CardTitle className="text-2xl">Add your Property</CardTitle>
        <CardDescription>
          This is how others will see you on the site.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <AddPropertyForm />
      </CardContent>
    </>
  );
}
